import Head from 'next/head';
//Utils
import requests from '../utils/requests';
//Components
import Header from '../components/Header';
import Navbar from '../components/Navbar';
import Feed from '../components/Feed';

export default function Home({ results }) {
  console.log(results);
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="hulu" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Navbar />
      <Feed results={results} />
    </div>
  )
}

export const getServerSideProps = async (context) => {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props : {
      results: request.results
    }
  }
}
